export interface GeneratedComponent {
  fileName: string;
  componentName: string;
  content: string;
}

export interface ComponentScaffoldResult {
  success: boolean;
  components: GeneratedComponent[];
  diagnostics: string[];
}

export class ComponentScaffoldService {
  generateFromComponents(componentNames: string[]): ComponentScaffoldResult {
    const diagnostics: string[] = [];

    diagnostics.push("Starting component scaffold generation.");

    const generatedComponents: GeneratedComponent[] = [];

    for (const componentName of componentNames) {
      generatedComponents.push({
        fileName: `${componentName}.js`,
        componentName,
        content: this.generateReactComponent(componentName),
      });
    }

    diagnostics.push(
      `Generated ${generatedComponents.length} component scaffold(s).`,
    );

    diagnostics.push("Component scaffold generation completed successfully.");

    return {
      success: true,
      components: generatedComponents,
      diagnostics,
    };
  }

  private generateReactComponent(componentName: string): string {
    return `
export default function ${componentName}() {
  return (
    <div className="bg-white rounded-xl shadow-sm border p-4">
      <h3 className="text-lg font-semibold">
        ${componentName}
      </h3>

      <p className="text-sm text-gray-500 mt-2">
        Generated by MundiCodeLens.
      </p>
    </div>
  );
}
`.trim();
  }
}
