import { FinanceUiTemplateService } from "./finance-ui-template-service";

export interface SemanticComponentTemplate {
  componentName: string;
  template: string;
}

export class SemanticComponentTemplateService {
  private readonly financeUiTemplateService = new FinanceUiTemplateService();

  getTemplate(componentName: string): SemanticComponentTemplate {
    const financeTemplate =
      this.financeUiTemplateService.getTemplate(componentName);

    if (financeTemplate) {
      return {
        componentName,
        template: financeTemplate.template,
      };
    }

    const template = this.resolveTemplate(componentName);

    return {
      componentName,
      template,
    };
  }

  private resolveTemplate(componentName: string): string {
    if (componentName.includes("Chart")) {
      return this.buildChartTemplate(componentName);
    }

    if (componentName.includes("Table")) {
      return this.buildTableTemplate(componentName);
    }

    if (componentName.includes("Widget")) {
      return this.buildWidgetTemplate(componentName);
    }

    if (componentName.includes("Filter")) {
      return this.buildFilterTemplate(componentName);
    }

    if (componentName.includes("Panel")) {
      return this.buildPanelTemplate(componentName);
    }

    if (componentName.includes("Summary")) {
      return this.buildSummaryTemplate(componentName);
    }

    return this.buildGenericTemplate(componentName);
  }

  private buildChartTemplate(componentName: string): string {
    return `
"use client";

export default function ${componentName}() {
  return (
    <div className="bg-white rounded-xl shadow-sm border p-4">
      <h3 className="text-lg font-semibold mb-4">
        ${componentName}
      </h3>

      <div className="h-64 flex items-center justify-center text-gray-500">
        Chart Visualization Placeholder
      </div>
    </div>
  );
}
`;
  }

  private buildTableTemplate(componentName: string): string {
    return `
export default function ${componentName}() {
  return (
    <div className="bg-white rounded-xl shadow-sm border p-4">
      <h3 className="text-lg font-semibold mb-4">
        ${componentName}
      </h3>

      <table className="w-full">
        <thead>
          <tr>
            <th>Name</th>
            <th>Status</th>
            <th>Value</th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td>Sample</td>
            <td>Active</td>
            <td>100</td>
          </tr>
        </tbody>
      </table>
    </div>
  );
}
`;
  }

  private buildWidgetTemplate(componentName: string): string {
    return `
export default function ${componentName}() {
  return (
    <div className="rounded-xl border p-4 bg-white shadow-sm">
      <h3 className="font-semibold">
        ${componentName}
      </h3>

      <p className="text-sm text-gray-500 mt-2">
        KPI Widget Placeholder
      </p>
    </div>
  );
}
`;
  }

  private buildFilterTemplate(componentName: string): string {
    return `
export default function ${componentName}() {
  return (
    <div className="bg-white rounded-xl border p-4 shadow-sm">
      <h3 className="font-semibold mb-3">
        ${componentName}
      </h3>

      <input
        className="border rounded-lg px-3 py-2 w-full"
        placeholder="Search..."
      />
    </div>
  );
}
`;
  }

  private buildPanelTemplate(componentName: string): string {
    return `
export default function ${componentName}() {
  return (
    <div className="bg-white rounded-xl border p-4 shadow-sm">
      <h3 className="font-semibold mb-3">
        ${componentName}
      </h3>

      <p>
        Panel Content Placeholder
      </p>
    </div>
  );
}
`;
  }

  private buildSummaryTemplate(componentName: string): string {
    return `
export default function ${componentName}() {
  return (
    <div className="bg-white rounded-xl border p-4 shadow-sm">
      <h3 className="font-semibold">
        ${componentName}
      </h3>

      <div className="text-3xl font-bold mt-2">
        ₦0
      </div>
    </div>
  );
}
`;
  }

  private buildGenericTemplate(componentName: string): string {
    return `
export default function ${componentName}() {
  return (
    <div className="bg-white rounded-xl shadow-sm border p-4">
      <h3 className="text-lg font-semibold">
        ${componentName}
      </h3>

      <p className="text-sm text-gray-500 mt-2">
        Generated by MundiCodeLens.
      </p>
    </div>
  );
}
`;
  }
}
